name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_TAG: ''  # Declared for schema validation in VS Code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract and sanitize branch name
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          SANITIZED_BRANCH=$(echo "$BRANCH_NAME" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_TAG=$SANITIZED_BRANCH" >> $GITHUB_ENV

      - name: Debug image tag
        run: |
          echo "Sanitized image tag: $IMAGE_TAG"
          
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/nestjs-mongo-api:${{ env.IMAGE_TAG }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/nestjs-mongo-api:${{ env.IMAGE_TAG }}
